services:
  - type: web
    name: recipe-db
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TURSO_DB_URL
        sync: false
      - key: TURSO_DB_AUTH_TOKEN
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
    previews:
      generateOnPullRequest: true
    
